/**
 * lib/stateRates.ts — numeric state income tax rates, keyed by ABBR.
 *
 * GENERATED by scripts/gen_state_rates.py from lib/states.ts. Do not edit
 * by hand: the generator parses incomeTaxNote and scripts/test_state_rates.py
 * asserts the two files agree, so an edit here would fail the test rather
 * than silently change a tax figure.
 *
 * Keyed by two-letter abbreviation because that is what stateTax() receives
 * from the tool forms ("CA", not "california"). SLUG_TO_ABBR covers callers
 * that pass a slug instead.
 *
 * low  = lowest marginal rate in the state's schedule
 * high = highest marginal rate in the state's schedule
 *
 * For a flat-tax state low === high. For a no-income-tax state both are 0.
 * These are MARGINAL rates, not effective rates — see stateTax() in
 * lib/calc.ts for how they are applied and what the model does not include.
 */
export type StateRate = { low: number; high: number };

export const STATE_INCOME_TAX: Record<string, StateRate> = {
  AL: { low: 2.0, high: 5.0 }, // alabama — progressive — Progressive state income tax, 2-5%
  AK: { low: 0.0, high: 0.0 }, // alaska — none — No state income tax
  AZ: { low: 2.5, high: 4.5 }, // arizona — progressive — Progressive state income tax, 2.5-4.5%
  AR: { low: 2.0, high: 4.9 }, // arkansas — progressive — Progressive state income tax, 2-4.9%
  CA: { low: 1.0, high: 13.3 }, // california — progressive — Progressive state income tax, 1-13.3%
  CO: { low: 4.4, high: 4.4 }, // colorado — flat — Flat state income tax, 4.4%
  CT: { low: 3.0, high: 6.99 }, // connecticut — progressive — Progressive state income tax, 3-6.99%
  DE: { low: 2.2, high: 6.6 }, // delaware — progressive — Progressive state income tax, 2.2-6.6%
  DC: { low: 4.0, high: 10.75 }, // district-of-columbia — progressive — Progressive income tax, 4-10.75%
  FL: { low: 0.0, high: 0.0 }, // florida — none — No state income tax
  GA: { low: 1.0, high: 5.75 }, // georgia — progressive — Progressive state income tax, 1-5.75%
  HI: { low: 1.4, high: 11.0 }, // hawaii — progressive — Progressive state income tax, 1.4-11%
  ID: { low: 5.8, high: 5.8 }, // idaho — flat — Flat state income tax, 5.8%
  IL: { low: 4.95, high: 4.95 }, // illinois — flat — Flat state income tax, 4.95%
  IN: { low: 3.05, high: 3.05 }, // indiana — flat — Flat state income tax, 3.05%
  IA: { low: 4.4, high: 5.7 }, // iowa — progressive — Progressive state income tax, 4.4-5.7%
  KS: { low: 3.1, high: 5.7 }, // kansas — progressive — Progressive state income tax, 3.1-5.7%
  KY: { low: 4.5, high: 4.5 }, // kentucky — flat — Flat state income tax, 4.5%
  LA: { low: 1.85, high: 4.25 }, // louisiana — progressive — Progressive state income tax, 1.85-4.25%
  ME: { low: 5.8, high: 7.15 }, // maine — progressive — Progressive state income tax, 5.8-7.15%
  MD: { low: 2.0, high: 5.75 }, // maryland — progressive — Progressive state income tax, 2-5.75%
  MA: { low: 5.0, high: 5.0 }, // massachusetts — flat — Flat state income tax, 5%
  MI: { low: 4.25, high: 4.25 }, // michigan — flat — Flat state income tax, 4.25%
  MN: { low: 5.35, high: 9.85 }, // minnesota — progressive — Progressive state income tax, 5.35-9.85%
  MS: { low: 4.0, high: 5.0 }, // mississippi — progressive — Progressive state income tax, 4-5%
  MO: { low: 2.0, high: 5.3 }, // missouri — progressive — Progressive state income tax, 2-5.3%
  MT: { low: 4.7, high: 5.9 }, // montana — progressive — Progressive state income tax, 4.7-5.9%
  NE: { low: 2.46, high: 6.64 }, // nebraska — progressive — Progressive state income tax, 2.46-6.64%
  NV: { low: 0.0, high: 0.0 }, // nevada — none — No state income tax
  NH: { low: 0.0, high: 0.0 }, // new-hampshire — none — No general income tax (interest/dividends only)
  NJ: { low: 1.4, high: 10.75 }, // new-jersey — progressive — Progressive state income tax, 1.4-10.75%
  NM: { low: 1.7, high: 5.9 }, // new-mexico — progressive — Progressive state income tax, 1.7-5.9%
  NY: { low: 4.0, high: 10.9 }, // new-york — progressive — Progressive state income tax, 4-10.9%
  NC: { low: 4.25, high: 4.25 }, // north-carolina — flat — Flat state income tax, 4.25%
  ND: { low: 1.95, high: 2.5 }, // north-dakota — progressive — Progressive state income tax, 1.95-2.5%
  OH: { low: 2.75, high: 3.5 }, // ohio — progressive — Progressive state income tax, 2.75-3.5%
  OK: { low: 0.25, high: 4.75 }, // oklahoma — progressive — Progressive state income tax, 0.25-4.75%
  OR: { low: 4.75, high: 9.9 }, // oregon — progressive — Progressive state income tax, 4.75-9.9%; no sales tax
  PA: { low: 3.07, high: 3.07 }, // pennsylvania — flat — Flat state income tax, 3.07%
  RI: { low: 3.75, high: 5.99 }, // rhode-island — progressive — Progressive state income tax, 3.75-5.99%
  SC: { low: 0.0, high: 6.4 }, // south-carolina — progressive — Progressive state income tax, 0-6.4%
  SD: { low: 0.0, high: 0.0 }, // south-dakota — none — No state income tax
  TN: { low: 0.0, high: 0.0 }, // tennessee — none — No earned income tax
  TX: { low: 0.0, high: 0.0 }, // texas — none — No state income tax
  UT: { low: 4.55, high: 4.55 }, // utah — flat — Flat state income tax, 4.55%
  VT: { low: 3.35, high: 8.75 }, // vermont — progressive — Progressive state income tax, 3.35-8.75%
  VA: { low: 2.0, high: 5.75 }, // virginia — progressive — Progressive state income tax, 2-5.75%
  WA: { low: 0.0, high: 0.0 }, // washington — none — No state income tax
  WV: { low: 2.36, high: 6.5 }, // west-virginia — progressive — Progressive state income tax, 2.36-6.5%
  WI: { low: 3.54, high: 7.65 }, // wisconsin — progressive — Progressive state income tax, 3.54-7.65%
  WY: { low: 0.0, high: 0.0 }, // wyoming — none — No state income tax
};

/** For callers that hold a slug rather than an abbreviation. */
export const SLUG_TO_ABBR: Record<string, string> = {
  "alabama": "AL",
  "alaska": "AK",
  "arizona": "AZ",
  "arkansas": "AR",
  "california": "CA",
  "colorado": "CO",
  "connecticut": "CT",
  "delaware": "DE",
  "district-of-columbia": "DC",
  "florida": "FL",
  "georgia": "GA",
  "hawaii": "HI",
  "idaho": "ID",
  "illinois": "IL",
  "indiana": "IN",
  "iowa": "IA",
  "kansas": "KS",
  "kentucky": "KY",
  "louisiana": "LA",
  "maine": "ME",
  "maryland": "MD",
  "massachusetts": "MA",
  "michigan": "MI",
  "minnesota": "MN",
  "mississippi": "MS",
  "missouri": "MO",
  "montana": "MT",
  "nebraska": "NE",
  "nevada": "NV",
  "new-hampshire": "NH",
  "new-jersey": "NJ",
  "new-mexico": "NM",
  "new-york": "NY",
  "north-carolina": "NC",
  "north-dakota": "ND",
  "ohio": "OH",
  "oklahoma": "OK",
  "oregon": "OR",
  "pennsylvania": "PA",
  "rhode-island": "RI",
  "south-carolina": "SC",
  "south-dakota": "SD",
  "tennessee": "TN",
  "texas": "TX",
  "utah": "UT",
  "vermont": "VT",
  "virginia": "VA",
  "washington": "WA",
  "west-virginia": "WV",
  "wisconsin": "WI",
  "wyoming": "WY",
};
