#!/usr/bin/env python3
"""Generate lib/stateRates.ts from lib/states.ts.

WHY: stateTax() applies a flat 5% to every state, while lib/states.ts already
records each state's ACTUAL schedule in incomeTaxNote ("1-13.3%" for California,
"4.95%" flat for Illinois, none for Texas). So a page titled "California Salary
After Tax Calculator" computed California the same as Illinois and the same as
every other state — the "promise vs delivery" mismatch an external audit flagged
on 2026-09-26.

This extracts the numbers already present, rather than introducing new claims.
Parsing display text at RUNTIME would be fragile, so it is parsed ONCE here and
written as data. scripts/test_state_rates.py then asserts the generated file
still agrees with lib/states.ts, so the two cannot drift apart silently.

Refuses to write if ANY state fails to parse — a silent default for a state
whose note changed shape is exactly how a wrong tax figure ships.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "lib", "states.ts")
OUT = os.path.join(ROOT, "lib", "stateRates.ts")

ENTRY = re.compile(
    r'\{\s*slug:\s*"(?P<slug>[^"]+)".*?'
    r'abbr:\s*"(?P<abbr>[A-Z]{2})".*?'
    r'incomeTax:\s*"(?P<kind>none|flat|progressive)".*?'
    r'incomeTaxNote:\s*"(?P<note>[^"]+)"',
    re.S,
)

RANGE = re.compile(r"(\d+(?:\.\d+)?)\s*-\s*(\d+(?:\.\d+)?)\s*%")
SINGLE = re.compile(r"(\d+(?:\.\d+)?)\s*%")

NONE_PHRASES = ("no state income tax", "no earned income tax", "no general income tax")


def parse(kind, note):
    low = note.lower()
    if kind == "none" or any(p in low for p in NONE_PHRASES):
        return 0.0, 0.0
    m = RANGE.search(note)
    if m:
        return float(m.group(1)), float(m.group(2))
    m = SINGLE.search(note)
    if m:
        r = float(m.group(1))
        return r, r
    return None


def main():
    text = open(SRC, encoding="utf-8").read()
    rows = []
    failures = []
    ABBR_BY_SLUG = {}

    for m in ENTRY.finditer(text):
        slug = m.group("slug")
        kind = m.group("kind")
        note = m.group("note")
        ABBR_BY_SLUG[slug] = m.group("abbr")
        got = parse(kind, note)
        if got is None:
            failures.append((slug, kind, note))
            continue
        rows.append((slug, kind, got[0], got[1], note))

    # A duplicate abbreviation would silently overwrite a state's rate.
    if len(set(ABBR_BY_SLUG.values())) != len(ABBR_BY_SLUG):
        seen = {}
        dupes = []
        for slug, abbr in ABBR_BY_SLUG.items():
            if abbr in seen:
                dupes.append((abbr, seen[abbr], slug))
            seen[abbr] = slug
        print(f"REFUSING TO WRITE — duplicate abbreviations: {dupes}")
        return 1

    if failures:
        print("REFUSING TO WRITE — unparseable income tax notes:")
        for slug, kind, note in failures:
            print(f"  {slug:24} kind={kind:12} note={note!r}")
        print("\nTeach the parser the new shape, then re-run.")
        return 1

    if not rows:
        print("REFUSING TO WRITE — parsed 0 states; the source shape must have changed.")
        return 1

    # Sanity: the two most distinctive states, so a parser that silently returns
    # 0 for everything cannot pass.
    by_slug = {r[0]: r for r in rows}
    for slug, want_low in (("california", 1.0), ("texas", 0.0), ("illinois", 4.95)):
        row = by_slug.get(slug)
        if not row or abs(row[2] - want_low) > 1e-9:
            print(f"REFUSING TO WRITE — {slug} parsed as {row and row[2]}, expected {want_low}")
            return 1

    lines = [
        "/**",
        " * lib/stateRates.ts — numeric state income tax rates, keyed by ABBR.",
        " *",
        " * GENERATED by scripts/gen_state_rates.py from lib/states.ts. Do not edit",
        " * by hand: the generator parses incomeTaxNote and scripts/test_state_rates.py",
        " * asserts the two files agree, so an edit here would fail the test rather",
        " * than silently change a tax figure.",
        " *",
        " * Keyed by two-letter abbreviation because that is what stateTax() receives",
        " * from the tool forms (\"CA\", not \"california\"). SLUG_TO_ABBR covers callers",
        " * that pass a slug instead.",
        " *",
        " * low  = lowest marginal rate in the state's schedule",
        " * high = highest marginal rate in the state's schedule",
        " *",
        " * For a flat-tax state low === high. For a no-income-tax state both are 0.",
        " * These are MARGINAL rates, not effective rates — see stateTax() in",
        " * lib/calc.ts for how they are applied and what the model does not include.",
        " */",
        "export type StateRate = { low: number; high: number };",
        "",
        "export const STATE_INCOME_TAX: Record<string, StateRate> = {",
    ]
    for slug, kind, low, high, note in sorted(rows, key=lambda r: r[0]):
        abbr = ABBR_BY_SLUG[slug]
        lines.append(f'  {abbr}: {{ low: {low}, high: {high} }}, // {slug} — {kind} — {note}')
    lines.append("};")
    lines.append("")
    lines.append("/** For callers that hold a slug rather than an abbreviation. */")
    lines.append("export const SLUG_TO_ABBR: Record<string, string> = {")
    for slug, _, _, _, _ in sorted(rows):
        lines.append(f'  "{slug}": "{ABBR_BY_SLUG[slug]}",')
    lines.append("};")
    lines.append("")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {OUT}")
    print(f"  states parsed : {len(rows)}")
    flat = sum(1 for r in rows if r[1] == "flat")
    prog = sum(1 for r in rows if r[1] == "progressive")
    none_ = sum(1 for r in rows if r[1] == "none")
    print(f"  none {none_}  flat {flat}  progressive {prog}")
    print(f"  california    : {by_slug['california'][2]}-{by_slug['california'][3]}%")
    print(f"  texas         : {by_slug['texas'][2]}-{by_slug['texas'][3]}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
